In [1]:
import numpy as np

In [2]:
A = np.array([10, 20, 30, 40])

In [3]:
mask = (A >= 20) & (A <= 30)

In [4]:
B = A[mask]

In [5]:
B

array([20, 30])

In [6]:
arr = np.arange(1, 10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
result = np.trace(arr)

In [8]:
print(result)

15


In [9]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [11]:
result = np.cross(arr1, arr2)
print(result)

[-3  6 -3]


In [12]:
matrix = np.random.randint(1, 100, 25).reshape(5, 5)
m = np.mean(matrix)
std = np.std(matrix)

print(m)
print(std)

50.48
31.81712746305046


In [13]:
np.random.seed(42)

matrix = np.eye(5) + 5

vector = np.random.randint(1, 11, (5, 1))
result = np.dot(matrix, vector)
print(result)

[[162.]
 [159.]
 [163.]
 [160.]
 [162.]]


In [14]:
matrix

array([[6., 5., 5., 5., 5.],
       [5., 6., 5., 5., 5.],
       [5., 5., 6., 5., 5.],
       [5., 5., 5., 6., 5.],
       [5., 5., 5., 5., 6.]])

In [15]:
result2 = np.matmul(matrix, vector)
result2

array([[162.],
       [159.],
       [163.],
       [160.],
       [162.]])

In [16]:
A = np.random.randint(1, 101, 9).reshape(3, 3)
B = np.random.randint(1, 101, 9).reshape(3, 3)


result = A * B
print(result)

result1 = np.multiply(A, B)
print(result1)

[[4399  174 6600]
 [2250 3344  200]
 [1536  180  462]]
[[4399  174 6600]
 [2250 3344  200]
 [1536  180  462]]


In [17]:
np.random.seed(42)
arr = np.random.randint(1, 1001, 1000)

cum_sum = np.cumsum(arr)

print(cum_sum)

[   103    539   1400   1671   1778   1850   2551   2572   3187   3309
   3776   3991   4322   4781   4869   5242   5342   6214   6878   7009
   7671   7980   8750   9094   9586  10000  10806  11192  11384  12340
  12617  12778  13238  13552  13574  13827  14575  15432  15993  16468
  16527  17038  17720  18196  18896  19872  20655  20845  21803  22490
  23448  24011  24887  25454  25698  26530  27035  27166  27651  28470
  29117  29138  29979  30146  30420  30808  31409  31725  31739  31981
  32758  33104  33669  34567  34907  34999  35366  36322  36777  37205
  37714  38490  39433  39468  39674  39755  40687  41249  42121  42509
  42511  42901  43467  43573  44345  45167  45644  46347  46749  47479
  48035  48197  48399  49357  50353  50623  51486  52302  52573  53029
  53491  54218  54470  55172  55468  56193  56913  57662  58000  58879
  58932  59724  60646  60863  61627  61815  62195  62688  62729  62886
  62901  63714  63779  64636  65475  65996  66340  66469  67117  67589
  6765

In [18]:
np.random.seed(42)
matrix = np.random.randint(10, 101, (10, 10))
min_value = np.min(matrix)
max_value = np.max(matrix)
print(min_value)
print(max_value)

min_index = np.unravel_index(np.argmin(matrix == min_value), matrix.shape)
max_index = np.unravel_index(np.argmax(matrix == max_value), matrix.shape)

print(min_index, max_index)

11
100
(0, 0) (2, 8)


In [19]:
matrix

array([[ 61,  24,  81,  70,  30,  92,  96,  84,  84,  97],
       [ 33,  12,  31,  62,  11,  97,  39,  47,  11,  73],
       [ 69,  30,  42,  85,  67,  31,  98,  58, 100,  68],
       [ 51,  69,  89,  24,  71,  71,  56,  71,  60,  64],
       [ 73,  12,  60,  16,  30,  82,  48,  27,  13,  98],
       [ 69,  23,  18,  99,  62,  11,  93,  69,  80,  53],
       [ 17,  56,  44,  87,  90,  45,  59,  13,  11,  15],
       [ 63,  13,  63,  72,  27,  99,  53,  43,  83,  71],
       [ 23,  57,  24,  81,  87,  96,  71,  49,  94,  89],
       [ 91,  62,  33,  35,  98,  69,  50,  38,  24,  54]])

In [20]:
matrix = np.random.rand(5, 5)
print(matrix)

max_value = np.max(matrix)(np.argmax(matrix), matrix.shape)



[[0.07455064 0.98688694 0.77224477 0.19871568 0.00552212]
 [0.81546143 0.70685734 0.72900717 0.77127035 0.07404465]
 [0.35846573 0.11586906 0.86310343 0.62329813 0.33089802]
 [0.06355835 0.31098232 0.32518332 0.72960618 0.63755747]
 [0.88721274 0.47221493 0.11959425 0.71324479 0.76078505]]


TypeError: 'numpy.float64' object is not callable

In [ ]:
import numpy as np



A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

B = A[1:3, 0:2]



B[0, 0] = 100

print(A)

In [ ]:
import numpy as np



A = np.arange(1, 17).reshape(4, 4)

B = A[:, ::-1]



print(B)

In [ ]:
import numpy as np

# Create a 1D array of 20 elements with random integers between 1 and 100
arr = np.random.randint(1, 100, 20)
print("Array:")
print(arr)

# Calculate the number of even and odd elements
evens = np.sum(arr % 2 == 0)
odds = np.sum(arr % 2 == 1)

print("Number of even numbers:", evens)
print("Number of odd numbers:", odds)

In [ ]:
import numpy as np

# Create a 1D array of 20 elements with random integers between 1 and 100
arr = np.random.randint(1, 100, 20)
print("Array:")
print(arr)

# Calculate the number of even and odd elements
evens = np.sum(arr % 2 == 0)
odds = np.sum(arr % 2 == 1)

print("Number of even numbers:", evens)
print("Number of odd numbers:", odds)

In [ ]:
data = {

    'Title': ['Inception', 'Dunkirk', 'Interstellar', 'The Prestige', 'Memento'],

    'Director': ['Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan', 'Christopher Nolan'],

    'Rating': [8.8, 7.9, 8.6, 8.5, 8.4]

}

In [ ]:
data

In [ ]:
import pandas as pd

In [ ]:
df = pd.DataFrame(data)
df

nolan_movie = df[df['Director'] == 'Christopher Nolan']

nolan_movie

In [ ]:
data = {

    'Category': ['Fruit', 'Vegetable', 'Fruit', 'Vegetable', 'Fruit', 'Vegetable'],

    'Name': ['Apple', 'Carrot', 'Banana', 'Potato', 'Grape', 'Onion'],

    'Price': [2, 1, 1.5, 0.5, 3, 1],

    'Quantity': [10, 20, 15, 30, 5, 40]

}



df = pd.DataFrame(data)



fruits = df[df['Category'] == 'Fruit']

total_fruit_value = fruits['Price'].sum() * fruits['Quantity'].sum()

print(total_fruit_value)

In [ ]:
import pandas as pd



data = {

    'Name': ['Alice', 'Bob', 'Charlie', 'David'],

    'Age': [25, 30, 35, 40],

    'City': ['New York', 'San Francisco', 'Los Angeles', 'Chicago']

}



df = pd.DataFrame(data)



result = df[df['Age'] >= 30].sort_values(by='Age', ascending=False).iloc[0]['City']

print(result)

In [ ]:
import pandas as pd



data = {

    'Product': ['A', 'B', 'C', 'A', 'B', 'C'],

    'Price': [100, 200, 300, 150, 250, 350],

    'Quantity': [10, 5, 7, 12, 8, 5]

}



df = pd.DataFrame(data)



total_revenue = (df['Price'] * df['Quantity']).sum()

average_price = df['Price'].mean()

print(total_revenue, average_price)

In [ ]:
data = {

    'Customer': ['Alice', 'Bob', 'Alice', 'Alice', 'Bob', 'Bob', 'Alice', 'Bob'],

    'Item': ['Pen', 'Pencil', 'Notebook', 'Eraser', 'Pen', 'Pencil', 'Notebook', 'Eraser'],

    'Price': [10, 5, 50, 20, 10, 5, 50, 20],

    'Quantity': [3, 4, 2, 5, 10, 6, 1, 2]

}

In [ ]:
df = pd.DataFrame(data)
df

In [ ]:
df['Total_Spent'] = df['Price'] * df['Quantity']
df

In [ ]:
item_summary = df.groupby('Item').agg({'Total_': 'sum'})